FROM openjdk:8-jre-slim

ARG PULSAR_VERSION=2.6.1
ARG SHORT_DISTRO_NAME=pulsar-$PULSAR_VERSION 
ARG DISTRO_NAME=apache-pulsar-$PULSAR_VERSION-bin
ARG PULSAR_HOME=/apache-pulsar-$PULSAR_VERSION
ARG BROKER_CONF=$PULSAR_HOME/conf/broker.conf
ARG CLIENT_CONF=$PULSAR_HOME/conf/client.conf
ARG DISCOVERY_CONF=$PULSAR_HOME/conf/discovery.conf
ARG PROXY_CONF=$PULSAR_HOME/conf/proxy.conf
ARG WEBSOCKET_CONF=$PULSAR_HOME/conf/websocket.conf
ARG ZOOKEEPER_CONF=$PULSAR_HOME/conf/zookeeper.conf
ARG GLOBAL_ZOOKEEPER_CONF=$PULSAR_HOME/conf/global_zookeeper.conf
ARG BOOKKEEPER_CONF=$PULSAR_HOME/conf/bookkeeper.conf
ARG STANDALONE_CONF=$PULSAR_HOME/conf/standalone.conf

ENV PULSAR_VERSION=$PULSAR_VERSION \ 
    BROKER_CONF=$BROKER_CONF \
    CLIENT_CONF=$CLIENT_CONF \
    DISCOVERY_CONF=$DISCOVERY_CONF \
    PROXY_CONF=$PROXY_CONF \
    WEBSOCKET_CONF=$WEBSOCKET_CONF \ 
    PATH=$PATH:$PULSAR_HOME/bin \ 
    BROKER__ZOOKEEPER_SERVERS= \
    BROKER__CONFIGURATION_STORE_SERVERS= \
    BROKER__BROKER_SERVICE_PORT=6650 \
    BROKER__BROKER_SERVICE_PORT_TLS= \
    BROKER__WEB_SERVICE_PORT=8080 \
    BROKER__WEB_SERVICE_PORT_TLS= \
    BROKER__BIND_ADDRESS=0.0.0.0 \
    BROKER__ADVERTISED_ADDRESS= \
    BROKER__NUM_IOTHREADS= \
    BROKER__NUM_HTTP_SERVER_THREADS= \
    BROKER__IS_RUNNING_STANDALONE= \
    BROKER__CLUSTER_NAME= \
    BROKER__FAILURE_DOMAINS_ENABLED=false \
    BROKER__ZOO_KEEPER_SESSION_TIMEOUT_MILLIS=30000 \
    BROKER__ZOO_KEEPER_OPERATION_TIMEOUT_SECONDS=30 \
    BROKER__ZOO_KEEPER_CACHE_EXPIRY_SECONDS=300 \
    BROKER__BROKER_SHUTDOWN_TIMEOUT_MS=60000 \
    BROKER__SKIP_BROKER_SHUTDOWN_ON_OOM=false \
    BROKER__BACKLOG_QUOTA_CHECK_ENABLED=true \
    BROKER__BACKLOG_QUOTA_CHECK_INTERVAL_IN_SECONDS=60 \
    BROKER__BACKLOG_QUOTA_DEFAULT_LIMIT_GB=-1 \
    BROKER__BACKLOG_QUOTA_DEFAULT_RETENTION_POLICY=producer_request_hold \
    BROKER__TTL_DURATION_DEFAULT_IN_SECONDS=0 \
    BROKER__ALLOW_AUTO_TOPIC_CREATION=true \
    BROKER__ALLOW_AUTO_TOPIC_CREATION_TYPE=non-partitioned \
    BROKER__ALLOW_AUTO_SUBSCRIPTION_CREATION=true \
    BROKER__DEFAULT_NUM_PARTITIONS=1 \
    BROKER__BROKER_DELETE_INACTIVE_TOPICS_ENABLED=true \
    BROKER__BROKER_DELETE_INACTIVE_TOPICS_FREQUENCY_SECONDS=60 \
    BROKER__BROKER_DELETE_INACTIVE_TOPICS_MODE=delete_when_no_subscriptions \
    BROKER__BROKER_DELETE_INACTIVE_TOPICS_MAX_INACTIVE_DURATION_SECONDS= \
    BROKER__MAX_PENDING_PUBLISHD_REQUESTS_PER_CONNECTION=1000 \
    BROKER__MESSAGE_EXPIRY_CHECK_INTERVAL_IN_MINUTES=5 \
    BROKER__ACTIVE_CONSUMER_FAILOVER_DELAY_TIME_MILLIS=1000 \
    BROKER__SUBSCRIPTION_EXPIRATION_TIME_MINUTES=0 \
    BROKER__SUBSCRIPTION_REDELIVERY_TRACKER_ENABLED=true \ 
    BROKER__SUBSCRIPTION_EXPIRY_CHECK_INTERVAL_IN_MINUTES=5 \
    BROKER__SUBSCRIPTION_KEY_SHARED_ENABLE=true \
    BROKER__SUBSCRIPTION_KEY_SHARED_USE_CONSISTENT_HASHING=false \
    BROKER__SUBSCRIPTION_KEY_SHARED_CONSISTENT_HASHING_REPLICA_POINTS=100 \
    BROKER__BROKER_DEDUPLICATION_ENABLED=false \
    BROKER__BROKER_DEDUPLICATION_MAX_NUMBER_OF_PRODUCERS=10000 \
    BROKER__BROKER_DEDUPLICATION_ENTRIES_INTERVAL=1000 \
    BROKER__BROKER_DEDUPLICATION_PRODUCER_INACTIVITY_TIMEOUT_MINUTES=360 \
    BROKER__DEFAULT_NUMBER_OF_NAMESPACE_BUNDLES=4 \
    BROKER__CLIENT_LIBRARY_VERSION_CHECK_ENABLED=false \
    BROKER__STATUS_FILE_PATH= \
    BROKER__PREFER_LATER_VERSIONS=false \
    BROKER__MAX_UNACKED_MESSAGES_PER_CONSUMER=50000 \
    BROKER__MAX_UNACKED_MESSAGES_PER_SUBSCRIPTION=200000 \
    BROKER__MAX_UNACKED_MESSAGES_PER_BROKER=0 \
    BROKER__MAX_UNACKED_MESSAGES_PER_SUBSCRIPTION_ON_BROKER_BLOCKED=0.16 \
    BROKER__TOPIC_PUBLISHER_THROTTLING_TICK_TIME_MILLIS=10 \
    BROKER__BROKER_PUBLISHER_THROTTLING_TICK_TIME_MILLIS=50 \
    BROKER__BROKER_PUBLISHER_THROTTLING_MAX_MESSAGE_RATE=0 \
    BROKER__BROKER_PUBLISHER_THROTTLING_MAX_BYTE_RATE=0 \
    BROKER__SUBSCRIBE_THROTTLING_RATE_PER_CONSUMER=0 \
    BROKER__SUBSCRIBE_RATE_PERIOD_PER_CONSUMER_IN_SECOND=30 \
    BROKER__DISPATCH_THROTTLING_RATE_PER_TOPIC_IN_MSG=0 \
    BROKER__DISPATCH_THROTTLING_RATE_PER_TOPIC_IN_BYTE=0 \
    BROKER__DISPATCH_THROTTLING_RATE_PER_SUBSCRIPTION_IN_MSG=0 \
    BROKER__DISPATCH_THROTTLING_RATE_PER_SUBSCRIPTION_IN_BYTE=0 \
    BROKER__DISPATCH_THROTTLING_RATE_PER_REPLICATOR_IN_MSG=0 \
    BROKER__DISPATCH_THROTTLING_RATE_PER_REPLICATOR_IN_BYTE=0 \
    BROKER__DISPATCH_THROTTLING_RATE_RELATIVE_TO_PUBLISH_RATE=false \
    BROKER__DISPATCH_THROTTLING_ON_NON_BACKLOG_CONSUMER_ENABLED=true \
    BROKER__DISPATCHER_MAX_READ_BATCH_SIZE=100 \
    BROKER__DISPATCHER_MAX_READ_SIZE_BYTES=5242880 \
    BROKER__DISPATCHER_MIN_READ_BATCH_SIZE=1 \
    BROKER__DISPATCHER_MAX_ROUND_ROBIN_BATCH_SIZE=20 \
    BROKER__PRECISE_DISPATCHER_FLOW_CONTROL=false \
    BROKER__MAX_CONCURRENT_LOOKUP_REQUEST=50000 \
    BROKER__MAX_CONCURRENT_TOPIC_LOAD_REQUEST=5000 \ 
    BROKER__MAX_CONCURRENT_NON_PERSISTENT_MESSAGE_PER_CONNECTION=1000 \
    BROKER__NUM_WORKER_THREADS_FOR_NON_PERSISTENT_TOPIC=8 \
    BROKER__ENABLE_PERSISTENT_TOPICS=true \
    BROKER__ENABLE_NON_PERSISTENT_TOPICS=true \
    BROKER__ENABLE_RUN_BOOKIE_TOGETHER=false \
    BROKER__ENABLE_RUN_BOOKIE_AUTO_RECOVERY_TOGETHER=false \
    BROKER__MAX_PRODUCERS_PER_TOPIC=0 \
    BROKER__MAX_CONSUMERS_PER_TOPIC=0 \
    BROKER__MAX_CONSUMERS_PER_SUBSCRIPTION=0 \
    BROKER__MAX_MESSAGE_SIZE=5242880 \
    BROKER__BROKER_SERVICE_COMPACTION_MONITOR_INTERVAL_IN_SECONDS=60 \
    BROKER__DELAYED_DELIVERY_ENABLED=true \
    BROKER__DELAYED_DELIVERY_TICK_TIME_MILLIS=1000 \
    BROKER__ACKNOWLEDGMENT_AT_BATCH_INDEX_LEVEL_ENABLED=false \
    BROKER__ENABLE_REPLICATED_SUBSCRIPTIONS=true \
    BROKER__REPLICATED_SUBSCRIPTIONS_SNAPSHOT_FREQUENCY_MILLIS=1000 \
    BROKER__REPLICATED_SUBSCRIPTIONS_SNAPSHOT_TIMEOUT_SECONDS=30 \
    BROKER__REPLICATED_SUBSCRIPTIONS_SNAPSHOT_MAX_CACHED_PER_SUBSCRIPTION=10 \
    BROKER__MAX_MESSAGE_PUBLISH_BUFFER_SIZE_IN_MB= \
    BROKER__MESSAGE_PUBLISH_BUFFER_CHECK_INTERVAL_IN_MILLIS=100 \
    BROKER__RETENTION_CHECK_INTERVAL_IN_SECONDS=120 \
    BROKER__MAX_NUM_PARTITIONS_PER_PARTITIONED_TOPIC=0 \
    BROKER__ZOOKEEPER_SESSION_EXPIRED_POLICY=shutdown \
    BROKER__SYSTEM_TOPIC_ENABLED=false \
    BROKER__TOPIC_LEVEL_POLICIES_ENABLED=false \
    BROKER__PROXY_ROLES= \
    BROKER__AUTHENTICATE_ORIGINAL_AUTH_DATA=false \
    BROKER__TLS_ENABLED=false \
    BROKER__TLS_CERT_REFRESH_CHECK_DURATION_SEC=300 \
    BROKER__TLS_CERTIFICATE_FILE_PATH= \
    BROKER__TLS_KEY_FILE_PATH= \
    BROKER__TLS_TRUST_CERTS_FILE_PATH= \
    BROKER__TLS_ALLOW_INSECURE_CONNECTION=false \
    BROKER__TLS_PROTOCOLS= \
    BROKER__TLS_CIPHERS= \
    BROKER__TLS_REQUIRE_TRUSTED_CLIENT_CERT_ON_CONNECT=false \ 
    BROKER__TLS_ENABLED_WITH_KEY_STORE=false \
    BROKER__TLS_PROVIDER= \
    BROKER__TLS_KEY_STORE_TYPE=JKS \
    BROKER__TLS_KEY_STORE= \
    BROKER__TLS_KEY_STORE_PASSWORD= \
    BROKER__TLS_TRUST_STORE_TYPE=JKS \
    BROKER__TLS_TRUST_STORE= \
    BROKER__TLS_TRUST_STORE_PASSWORD= \
    BROKER__BROKER_CLIENT_TLS_ENABLED_WITH_KEY_STORE=false \
    BROKER__BROKER_CLIENT_SSL_PROVIDER= \
    BROKER__BROKER_CLIENT_TLS_TRUST_STORE_TYPE=JKS \
    BROKER__BROKER_CLIENT_TLS_TRUST_STORE= \
    BROKER__BROKER_CLIENT_TLS_TRUST_STORE_PASSWORD= \
    BROKER__BROKER_CLIENT_TLS_CIPHERS= \
    BROKER__BROKER_CLIENT_TLS_PROTOCOLS= \
    BROKER__AUTHENTICATION_ENABLED=false \
    BROKER__AUTHENTICATION_PROVIDERS= \
    BROKER__AUTHENTICATION_REFRESH_CHECK_SECONDS=60 \
    BROKER__AUTHORIZATION_ENABLED=false \
    BROKER__AUTHORIZATION_PROVIDER=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider \
    BROKER__AUTHORIZATION_ALLOW_WILDCARDS_MATCHING=false \
    BROKER__SUPER_USER_ROLES= \
    BROKER__BROKER_CLIENT_TLS_ENABLED=false \
    BROKER__BROKER_CLIENT_AUTHENTICATION_PLUGIN= \
    BROKER__BROKER_CLIENT_AUTHENTICATION_PARAMETERS= \
    BROKER__BROKER_CLIENT_TRUST_CERTS_FILE_PATH= \
    BROKER__ATHENZ_DOMAIN_NAMES= \
    BROKER__ANONYMOUS_USER_ROLE= \
    BROKER__TOKEN_SECRET_KEY= \
    BROKER__TOKEN_PUBLIC_KEY= \
    BROKER__TOKEN_AUTH_CLAIM= \
    BROKER__TOKEN_AUDIENCE_CLAIM= \
    BROKER__TOKEN_AUDIENCE= \
    BROKER__SASL_JAAS_CLIENT_ALLOWED_IDS= \
    BROKER__SASL_JAAS_BROKER_SECTION_NAME= \
    BROKER__HTTP_MAX_REQUEST_SIZE=-1 \
    BROKER__BOOKKEEPER_METADATA_SERVICE_URI= \
    BROKER__BOOKKEEPER_CLIENT_AUTHENTICATION_PLUGIN= \ 
    BROKER__BOOKKEEPER_CLIENT_AUTHENTICATION_PARAMETERS_NAME= \
    BROKER__BOOKKEEPER_CLIENT_AUTHENTICATION_PARAMETERS= \
    BROKER__BOOKKEEPER_CLIENT_TIMEOUT_IN_SECONDS=30 \
    BROKER__BOOKKEEPER_CLIENT_SPECULATIVE_READ_TIMEOUT_IN_MILLIS=0 \
    BROKER__BOOKKEEPER_USE_V2_WIRE_PROTOCOL=true \
    BROKER__BOOKKEEPER_CLIENT_HEALTH_CHECK_ENABLED=true \
    BROKER__BOOKKEEPER_CLIENT_HEALTH_CHECK_INTERVAL_SECONDS=60 \
    BROKER__BOOKKEEPER_CLIENT_HEALTH_CHECK_ERROR_THRESHOLD_PER_INTERVAL=5 \
    BROKER__BOOKKEEPER_CLIENT_HEALTH_CHECK_QUARANTINE_TIME_IN_SECONDS=1800 \
    BROKER__BOOKKEEPER_GET_BOOKIE_INFO_INTERVAL_SECONDS=86400 \
    BROKER__BOOKKEEPER_GET_BOOKIE_INFO_RETRY_INTERVAL_SECONDS=60 \
    BROKER__BOOKKEEPER_CLIENT_RACKAWARE_POLICY_ENABLED=true \
    BROKER__BOOKKEEPER_CLIENT_REGIONAWARE_POLICY_ENABLED=false \
    BROKER__BOOKKEEPER_CLIENT_REORDER_READ_SEQUENCE_ENABLED=false \
    BROKER__BOOKKEEPER_CLIENT_ISOLATION_GROUPS= \
    BROKER__BOOKKEEPER_CLIENT_SECONDARY_ISOLATION_GROUPS= \
    BROKER__BOOKKEEPER_CLIENT_MIN_AVAILABLE_BOOKIES_IN_ISOLATION_GROUPS= \
    BROKER__BOOKKEEPER_ENABLE_STICKY_READS=false \
    BROKER__BOOKKEEPER_TLSPROVIDER_FACTORY_CLASS=org.apache.bookkeeper.tls.TLSContextFactory \
    BROKER__BOOKKEEPER_TLSCLIENT_AUTHENTICATION=false \
    BROKER__BOOKKEEPER_TLSKEY_FILE_TYPE=PEM \
    BROKER__BOOKKEEPER_TLSTRUST_CERT_TYPES=PEM \
    BROKER__BOOKKEEPER_TLSKEY_STORE_PASSWORD_PATH= \
    BROKER__BOOKKEEPER_TLSTRUST_STORE_PASSWORD_PATH= \
    BROKER__BOOKKEEPER_TLSKEY_FILE_PATH= \
    BROKER__BOOKKEEPER_TLSCERTIFICATE_FILE_PATH= \
    BROKER__BOOKKEEPER_TLSTRUST_CERTS_FILE_PATH= \
    BROKER__BOOKKEEPER_DISK_WEIGHT_BASED_PLACEMENT_ENABLED=false \
    BROKER__BOOKKEEPER_EXPLICIT_LAC_INTERVAL_IN_MILLS=0 \
    BROKER__MANAGED_LEDGER_DEFAULT_ENSEMBLE_SIZE=2 \
    BROKER__MANAGED_LEDGER_DEFAULT_WRITE_QUORUM=2 \
    BROKER__MANAGED_LEDGER_DEFAULT_ACK_QUORUM=2 \
    BROKER__MANAGED_LEDGER_DIGEST_TYPE=CRC32C \
    BROKER__MANAGED_LEDGER_NUM_WORKER_THREADS=8 \
    BROKER__MANAGED_LEDGER_NUM_SCHEDULER_THREADS=8 \
    BROKER__MANAGED_LEDGER_CACHE_SIZE_MB= \
    BROKER__MANAGED_LEDGER_CACHE_COPY_ENTRIES=false \
    BROKER__MANAGED_LEDGER_CACHE_EVICTION_WATERMARK=0.9 \ 
    BROKER__MANAGED_LEDGER_CACHE_EVICTION_FREQUENCY=100.0 \
    BROKER__MANAGED_LEDGER_CACHE_EVICTION_TIME_THRESHOLD_MILLIS=1000 \
    BROKER__MANAGED_LEDGER_CURSOR_BACKLOGGED_THRESHOLD=1000 \
    BROKER__MANAGED_LEDGER_DEFAULT_MARK_DELETE_RATE_LIMIT=1.0 \
    BROKER__MANAGED_LEDGER_MAX_ENTRIES_PER_LEDGER=50000 \
    BROKER__MANAGED_LEDGER_MIN_LEDGER_ROLLOVER_TIME_MINUTES=10 \
    BROKER__MANAGED_LEDGER_MAX_LEDGER_ROLLOVER_TIME_MINUTES=240 \
    BROKER__MANAGED_LEDGER_MAX_SIZE_PER_LEDGER_MBYTES=2048 \
    BROKER__MANAGED_LEDGER_OFFLOAD_DELETION_LAG_MS=14400000 \
    BROKER__MANAGED_LEDGER_OFFLOAD_AUTO_TRIGGER_SIZE_THRESHOLD_BYTES=-1 \
    BROKER__MANAGED_LEDGER_CURSOR_MAX_ENTRIES_PER_LEDGER=50000 \
    BROKER__MANAGED_LEDGER_CURSOR_ROLLOVER_TIME_IN_SECONDS=14400 \
    BROKER__MANAGED_LEDGER_MAX_UNACKED_RANGES_TO_PERSIST=10000 \
    BROKER__MANAGED_LEDGER_MAX_UNACKED_RANGES_TO_PERSIST_IN_ZOO_KEEPER=1000 \
    BROKER__AUTO_SKIP_NON_RECOVERABLE_DATA=false \
    BROKER__MANAGED_LEDGER_METADATA_OPERATIONS_TIMEOUT_SECONDS=60 \
    BROKER__MANAGED_LEDGER_READ_ENTRY_TIMEOUT_SECONDS=0 \
    BROKER__MANAGED_LEDGER_ADD_ENTRY_TIMEOUT_SECONDS=0 \
    BROKER__MANAGED_LEDGER_PROMETHEUS_STATS_LATENCY_ROLLOVER_SECONDS=60 \
    BROKER__MANAGED_LEDGER_TRACE_TASK_EXECUTION=true \
    BROKER__MANAGED_LEDGER_NEW_ENTRIES_CHECK_DELAY_IN_MILLIS=10 \
    BROKER__LOAD_BALANCER_ENABLED=true \
    BROKER__LOAD_BALANCER_REPORT_UPDATE_THRESHOLD_PERCENTAGE=10 \
    BROKER__LOAD_BALANCER_REPORT_UPDATE_MAX_INTERVAL_MINUTES=15 \
    BROKER__LOAD_BALANCER_HOST_USAGE_CHECK_INTERVAL_MINUTES=1 \
    BROKER__LOAD_BALANCER_SHEDDING_ENABLED=true \
    BROKER__LOAD_BALANCER_SHEDDING_INTERVAL_MINUTES=1 \
    BROKER__LOAD_BALANCER_SHEDDING_GRACE_PERIOD_MINUTES=30 \
    BROKER__LOAD_BALANCER_BROKER_MAX_TOPICS=50000 \
    BROKER__LOAD_BALANCER_BROKER_OVERLOADED_THRESHOLD_PERCENTAGE=85 \
    BROKER__LOAD_BALANCER_RESOURCE_QUOTA_UPDATE_INTERVAL_MINUTES=15 \
    BROKER__LOAD_BALANCER_AUTO_BUNDLE_SPLIT_ENABLED=true \
    BROKER__LOAD_BALANCER_AUTO_UNLOAD_SPLIT_BUNDLES_ENABLED=true \
    BROKER__LOAD_BALANCER_NAMESPACE_BUNDLE_MAX_TOPICS=1000 \
    BROKER__LOAD_BALANCER_NAMESPACE_BUNDLE_MAX_SESSIONS=1000 \
    BROKER__LOAD_BALANCER_NAMESPACE_BUNDLE_MAX_MSG_RATE=30000 \
    BROKER__LOAD_BALANCER_NAMESPACE_BUNDLE_MAX_BANDWIDTH_MBYTES=100 \
    BROKER__LOAD_BALANCER_NAMESPACE_MAXIMUM_BUNDLES=128 \ 
    BROKER__LOAD_BALANCER_OVERRIDE_BROKER_NIC_SPEED_GBPS= \
    BROKER__LOAD_MANAGER_CLASS_NAME=org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl \
    BROKER__SUPPORTED_NAMESPACE_BUNDLE_SPLIT_ALGORITHMS=range_equally_divide,topic_count_equally_divide \
    BROKER__DEFAULT_NAMESPACE_BUNDLE_SPLIT_ALGORITHM=range_equally_divide \
    BROKER__LOAD_BALANCER_LOAD_SHEDDING_STRATEGY=org.apache.pulsar.broker.loadbalance.impl.OverloadShedder \
    BROKER__LOAD_BALANCER_BROKER_THRESHOLD_SHEDDER_PERCENTAGE=10 \
    BROKER__LOAD_BALANCER_HISTORY_RESOURCE_PERCENTAGE=0.9 \
    BROKER__LOAD_BALANCER_BANDWITH_IN_RESOURCE_WEIGHT=1.0 \
    BROKER__LOAD_BALANCER_BANDWITH_OUT_RESOURCE_WEIGHT=1.0 \
    BROKER__LOAD_BALANCER_CPURESOURCE_WEIGHT=1.0 \
    BROKER__LOAD_BALANCER_MEMORY_RESOURCE_WEIGHT=1.0 \
    BROKER__LOAD_BALANCER_DIRECT_MEMORY_RESOURCE_WEIGHT=1.0 \
    BROKER__LOAD_BALANCER_BUNDLE_UNLOAD_MIN_THROUGHPUT_THRESHOLD=10 \
    BROKER__REPLICATION_METRICS_ENABLED=true \
    BROKER__REPLICATION_CONNECTIONS_PER_BROKER=16 \
    BROKER__REPLICATION_PRODUCER_QUEUE_SIZE=1000 \
    BROKER__REPLICATOR_PREFIX=pulsar.repl \
    BROKER__REPLICATION_POLICY_CHECK_DURATION_SECONDS=600 \
    BROKER__DEFAULT_RETENTION_TIME_IN_MINUTES=0 \
    BROKER__DEFAULT_RETENTION_SIZE_IN_MB=0 \
    BROKER__KEEP_ALIVE_INTERVAL_SECONDS=30 \
    BROKER__BOOTSTRAP_NAMESPACES= \
    BROKER__WEB_SOCKET_SERVICE_ENABLED=false \
    BROKER__WEB_SOCKET_NUM_IO_THREADS=8 \
    BROKER__WEB_SOCKET_CONNECTIONS_PER_BROKER=8 \
    BROKER__WEB_SOCKET_SESSION_IDLE_TIMEOUT_MILLIS=300000 \
    BROKER__WEB_SOCKET_MAX_TEXT_FRAME_SIZE=1048576 \
    BROKER__EXPOSE_TOPIC_LEVEL_METRICS_IN_PROMETHEUS=true \
    BROKER__EXPOSE_CONSUMER_LEVEL_METRICS_IN_PROMETHEUS=false \
    BROKER__FUNCTIONS_WORKER_ENABLED=false \
    BROKER__EXPOSE_PUBLISHER_STATS=true \
    BROKER__STATS_UPDATE_FREQUENCY_IN_SECS=60 \
    BROKER__STATS_UPDATE_INITIAL_DELAY_IN_SECS=60 \
    BROKER__EXPOSE_PRECISE_BACKLOG_IN_PROMETHEUS=false \
    BROKER__SCHEMA_REGISTRY_STORAGE_CLASS_NAME=org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorageFactory \
    BROKER__IS_SCHEMA_VALIDATION_ENFORCED=false \
    BROKER__OFFLOADERS_DIRECTORY=./offloaders \ 
    BROKER__MANAGED_LEDGER_OFFLOAD_DRIVER= \
    BROKER__MANAGED_LEDGER_OFFLOAD_MAX_THREADS=2 \
    BROKER__MANAGED_LEDGER_OFFLOAD_PREFETCH_ROUNDS=1 \
    BROKER__MANAGED_LEDGER_UNACKED_RANGES_OPEN_CACHE_SET_ENABLED=true \
    BROKER__S3_MANAGED_LEDGER_OFFLOAD_REGION= \
    BROKER__S3_MANAGED_LEDGER_OFFLOAD_BUCKET= \
    BROKER__S3_MANAGED_LEDGER_OFFLOAD_SERVICE_ENDPOINT= \
    BROKER__S3_MANAGED_LEDGER_OFFLOAD_MAX_BLOCK_SIZE_IN_BYTES=67108864 \
    BROKER__S3_MANAGED_LEDGER_OFFLOAD_READ_BUFFER_SIZE_IN_BYTES=1048576 \
    BROKER__GCS_MANAGED_LEDGER_OFFLOAD_REGION= \
    BROKER__GCS_MANAGED_LEDGER_OFFLOAD_BUCKET= \
    BROKER__GCS_MANAGED_LEDGER_OFFLOAD_MAX_BLOCK_SIZE_IN_BYTES=67108864 \
    BROKER__GCS_MANAGED_LEDGER_OFFLOAD_READ_BUFFER_SIZE_IN_BYTES=1048576 \
    BROKER__GCS_MANAGED_LEDGER_OFFLOAD_SERVICE_ACCOUNT_KEY_FILE= \
    BROKER__FILE_SYSTEM_PROFILE_PATH=../conf/filesystem_offload_core_site.xml \
    BROKER__FILE_SYSTEM_URI= \
    BROKER__GLOBAL_ZOOKEEPER_SERVERS= \
    BROKER__REPLICATION_TLS_ENABLED=false \
    BROKER__BROKER_SERVICE_PURGE_INACTIVE_FREQUENCY_IN_SECONDS=60 \
    BROKER__TRANSACTION_COORDINATOR_ENABLED=true \
    BROKER__TRANSACTION_METADATA_STORE_PROVIDER_CLASS_NAME=org.apache.pulsar.transaction.coordinator.impl.InMemTransactionMetadataStoreProvider 

ENV CLIENT__WEB_SERVICE_URL=http://localhost:8080/ \
    CLIENT__BROKER_SERVICE_URL=pulsar://localhost:6650/ \
    CLIENT__AUTH_PLUGIN= \
    CLIENT__AUTH_PARAMS= \
    CLIENT__TLS_ALLOW_INSECURE_CONNECTION=false \
    CLIENT__TLS_ENABLE_HOSTNAME_VERIFICATION=false \
    CLIENT__TLS_TRUST_CERTS_FILE_PATH= \
    CLIENT__USE_KEY_STORE_TLS=false \
    CLIENT__TLS_TRUST_STORE_TYPE=JKS \
    CLIENT__TLS_TRUST_STORE_PATH= \
    CLIENT__TLS_TRUST_STORE_PASSWORD= \
    DISCOVERY__ZOOKEEPER_SERVERS= \
    DISCOVERY__CONFIGURATION_STORE_SERVERS= \
    DISCOVERY__ZOOKEEPER_SESSION_TIMEOUT_MS=30000 \
    DISCOVERY__ZOO_KEEPER_CACHE_EXPIRY_SECONDS=300 \
    DISCOVERY__SERVICE_PORT=6650 \
    DISCOVERY__SERVICE_PORT_TLS= \
    DISCOVERY__WEB_SERVICE_PORT=8080 \
    DISCOVERY__WEB_SERVICE_PORT_TLS= \
    DISCOVERY__BIND_ON_LOCALHOST=false \
    DISCOVERY__AUTHENTICATION_ENABLED=false \
    DISCOVERY__AUTHENTICATION_PROVIDERS= \
    DISCOVERY__AUTHORIZATION_ENABLED=false \
    DISCOVERY__AUTHORIZATION_PROVIDERS=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider \
    DISCOVERY__SUPER_USER_ROLES= \
    DISCOVERY__AUTHORIZATION_ALLOW_WILDCARDS_MATCHING=false \
    DISCOVERY__TLS_ENABLED=false \
    DISCOVERY__TLS_CERTIFICATE_FILE_PATH= \
    DISCOVERY__TLS_KEY_FILE_PATH= \
    DISCOVERY__TLS_REQUIRE_TRUSTED_CLIENT_CERT_ON_CONNECT=false \
    DISCOVERY__TLS_CERT_REFRESH_CHECK_DURATION_SEC=300 \
    DISCOVERY__GLOBAL_ZOOKEEPER_SERVERS= \
    PROXY__ZOOKEEPER_SERVERS= \
    PROXY__CONFIGURATION_STORE_SERVERS= \
    PROXY__BROKER_SERVICE_URL= \
    PROXY__BROKER_SERVICE_URLTLS= \
    PROXY__BROKER_WEB_SERVICE_URL= \
    PROXY__BROKER_WEB_SERVICE_URLTLS= \
    PROXY__FUNCTION_WORKER_WEB_SERVICE_URL= \
    PROXY__FUNCTION_WORKER_WEB_SERVICE_URLTLS= \
    PROXY__ZOOKEEPER_SESSION_TIMEOUT_MS=30000 \
    PROXY__ZOO_KEEPER_CACHE_EXPIRY_SECONDS=300 \
    PROXY__ADVERTISED_ADDRESS= \
    PROXY__SERVICE_PORT=6650 \
    PROXY__SERVICE_PORT_TLS= \
    PROXY__WEB_SERVICE_PORT=8080 \
    PROXY__WEB_SERVICE_PORT_TLS= \
    PROXY__STATUS_FILE_PATH= \
    PROXY__PROXY_LOG_LEVEL=0 \
    PROXY__SUPER_USER_ROLES= \
    PROXY__AUTHORIZATION_ENABLED=false \
    PROXY__AUTHORIZATION_PROVIDER=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider \
    PROXY__FORWARD_AUTHORIZATION_CREDENTIALS=false \
    PROXY__AUTHENTICATION_ENABLED=false \
    PROXY__AUTHENTICATION_PROVIDERS= \
    PROXY__ANONYMOUS_USER_ROLE= \
    PROXY__BROKER_CLIENT_AUTHENTICATION_PLUGIN= \
    PROXY__BROKER_CLIENT_AUTHENTICATION_PARAMETERS= \
    PROXY__BROKER_CLIENT_TRUST_CERTS_FILE_PATH= \
    PROXY__TLS_ENABLED_WITH_BROKER=false \
    PROXY__TLS_CERT_REFRESH_CHECK_DURATION_SEC=300 \
    PROXY__MAX_CONCURRENT_INBOUND_CONNECTIONS=10000 \
    PROXY__MAX_CONCURRENT_LOOKUP_REQUESTS=50000 \
    PROXY__TLS_ENABLED_IN_PROXY=false \
    PROXY__TLS_CERTIFICATE_FILE_PATH= \
    PROXY__TLS_KEY_FILE_PATH= \
    PROXY__TLS_TRUST_CERTS_FILE_PATH= \
    PROXY__TLS_ALLOW_INSECURE_CONNECTION=false \
    PROXY__TLS_HOSTNAME_VERIFICATION_ENABLED=false \
    PROXY__TLS_PROTOCOLS= \
    PROXY__TLS_CIPHERS= \
    PROXY__TLS_REQUIRE_TRUSTED_CLIENT_CERT_ON_CONNECT=false \
    PROXY__HTTP_REVERSE_PROXY_CONFIGS= \
    PROXY__HTTP_OUTPUT_BUFFER_SIZE=32768 \
    PROXY__HTTP_NUM_THREADS= \
    PROXY__TOKEN_SECRET_KEY= \
    PROXY__TOKEN_PUBLIC_KEY= \
    PROXY__TOKEN_AUTH_CLAIM= \
    PROXY__TOKEN_AUDIENCE_CLAIM= \
    PROXY__TOKEN_AUDIENCE= \
    PROXY__GLOBAL_ZOOKEEPER_SERVERS= \
    WEBSOCKET__CONFIGURATION_STORE_SERVERS= \
    WEBSOCKET__ZOO_KEEPER_SESSION_TIMEOUT_MILLIS=30000 \
    WEBSOCKET__ZOO_KEEPER_CACHE_EXPIRY_SECONDS=300 \
    WEBSOCKET__SERVICE_URL= \
    WEBSOCKET__SERVICE_URL_TLS= \
    WEBSOCKET__BROKER_SERVICE_URL= \
    WEBSOCKET__BROKER_SERVICE_URL_TLS= \
    WEBSOCKET__WEB_SERVICE_PORT=8080 \
    WEBSOCKET__WEB_SERVICE_PORT_TLS= \
    WEBSOCKET__STATUS_FILE_PATH= \
    WEBSOCKET__BIND_ADDRESS=0.0.0.0 \
    WEBSOCKET__CLUSTER_NAME= \
    WEBSOCKET__WEB_SOCKET_NUM_IO_THREADS=8 \
    WEBSOCKET__NUM_HTTP_SERVER_THREADS= \
    WEBSOCKET__WEB_SOCKET_CONNECTIONS_PER_BROKER=8 \
    WEBSOCKET__WEB_SOCKET_SESSION_IDLE_TIMEOUT_MILLIS=300000 \
    WEBSOCKET__WEB_SOCKET_MAX_TEXT_FRAME_SIZE=1048576 \
    WEBSOCKET__AUTHENTICATION_ENABLED=false \
    WEBSOCKET__AUTHENTICATION_PROVIDERS= \
    WEBSOCKET__AUTHORIZATION_ENABLED=false \
    WEBSOCKET__AUTHORIZATION_PROVIDER=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider \
    WEBSOCKET__AUTHORIZATION_ALLOW_WILDCARDS_MATCHING=false \
    WEBSOCKET__SUPER_USER_ROLES= \
    WEBSOCKET__BROKER_CLIENT_TLS_ENABLED=false \
    WEBSOCKET__BROKER_CLIENT_AUTHENTICATION_PLUGIN= \
    WEBSOCKET__BROKER_CLIENT_AUTHENTICATION_PARAMETERS= \
    WEBSOCKET__BROKER_CLIENT_TRUST_CERTS_FILE_PATH= \
    WEBSOCKET__ANONYMOUS_USER_ROLE= \
    WEBSOCKET__TLS_ENABLED=false \
    WEBSOCKET__TLS_ALLOW_INSECURE_CONNECTION=false \
    WEBSOCKET__TLS_CERTIFICATE_FILE_PATH= \
    WEBSOCKET__TLS_KEY_FILE_PATH= \
    WEBSOCKET__TLS_TRUST_CERTS_FILE_PATH= \
    WEBSOCKET__TLS_REQUIRE_TRUSTED_CLIENT_CERT_ON_CONNECT=false \
    WEBSOCKET__TLS_CERT_REFRESH_CHECK_DURATION_SEC=300 \
    WEBSOCKET__GLOBAL_ZOOKEEPER_SERVERS=  

# Add pulsar user
RUN set -eux \
    && groupadd -r pulsar \
    && useradd -r -g pulsar pulsar \ 
# Install required packges
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        dirmngr \
        gosu \
        gnupg2 \
        netcat \
        wget \
    && rm -rf /var/lib/apt/lists/* \
# Verify that gosu binary works
    && gosu nobody true \ 
# Download Apache BookKeeper, verify its PGP signature, untar and clean up
    && download() { \
        local f="$1"; shift; \
        local distFile="$1"; shift; \
        local success=; \
        local distUrl=; \
        for distUrl in \
            'https://www.apache.org/dyn/closer.cgi?action=download&filename=' \
            https://www-us.apache.org/dist/ \
            https://www.apache.org/dist/ \
            https://archive.apache.org/dist/ \
        ; do \
            if wget -O "$f" "$distUrl$distFile" && [ -s "$f" ]; then \
                success=1; \
                break; \
            fi; \
        done; \
        [ -n "$success" ]; \
    } \
    && download "$DISTRO_NAME.tar.gz" "pulsar/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz" \
    && download "$DISTRO_NAME.tar.gz.asc" "pulsar/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz.asc" \
    && download "$DISTRO_NAME.tar.gz.sha512" "pulsar/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz.sha512" \
    && verify() { \
        msg=$(gpg2 --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz" 2>&1); \
        if (( $? )); then \
            key=$(echo $msg | sed -E '1~2d; s/(.*key )(.*)/\2/'); \
            gpg2 --keyserver ha.pool.sks-keyservers.net --recv-key "$key" || \
            gpg2 --keyserver pgp.mit.edu --recv-key "$key" || \
            gpg2 --keyserver keyserver.pgp.com --recv-key "$key"; \
            gpg2 --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz" 2>&1; \
        fi \
    } \ 
    && sha512sum -c ${DISTRO_NAME}.tar.gz.sha512 \
    && export GNUPGHOME="$(mktemp -d)" \ 
    && wget https://www.apache.org/dist/pulsar/KEYS \
    && gpg2 --import KEYS \
    && verify \
    && tar -vzxf "$DISTRO_NAME.tar.gz" \
    && rm -rf "$GNUPGHOME" "$DISTRO_NAME.tar.gz" "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz.sha512" \
       "$BROKER_CONF" "$CLIENT_CONF" "$DISCOVERY_CONF" "$PROXY_CONF" "$WEBSOCKET_CONF" \
       "$ZOOKEEPER_CONF" "$GLOBAL_ZOOKEEPER_CONF" "$BOOKKEEPER_CONF" "$STANDALONE_CONF"  \
    && chown -R pulsar:pulsar "$PULSAR_HOME" 

WORKDIR $PULSAR_HOME 
EXPOSE 3181 8080 4181 
COPY docker-entrypoint.sh gen-broker.conf gen-client.conf gen-proxy.conf gen-discovery.conf gen-websocket.conf /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["pulsar","broker"]
#::END::
