#!/bin/bash 
#
# TODO Implement deleteCluster function within docker-entrypoint.sh
#

source cluster.conf
source util-common

DELETE_CMD="docker run --rm"
[[ ! -z "$NETWORK_NAME" ]] && DELETE_CMD+=" --network $NETWORK_NAME"
DELETE_CMD+=" --env BROKER__ZOOKEEPER_SERVERS=$BROKER__ZOOKEEPER_SERVERS 
	--env BROKER__CONFIGURATION_STORE_SERVERS=$BROKER__CONFIGURATION_STORE_SERVERS 
	--env BROKER__BOOKKEEPER_METADATA_SERVICE_URI=$BROKER__BOOKKEEPER_METADATA_SERVICE_URI 
	$IMAGE deleteCluster $CLUSTER_NAME $PULSAR_HOSTNAME"

echo $DELETE_CMD
echo ">>> NOT YET IMPLEMENTED <<<<"

#::END:: 
