#!/bin/bash 

source cluster.conf

abort() 
{
	echo "$1 not set. Aborting..."
	exit 1
}

[[ -z "$CLUSTER_NAME" ]] && abort "Cluster name"
[[ -z "$PULSAR_HOSTNAME" ]] && abort "Pulsar hostname"
[[ -z "$IMAGE" ]] && abort "Image name"
[[ -z "$BROKER__ZOOKEEPER_SERVERS" ]] && abort "Zookeeper servers"
[[ -z "$BROKER__CONFIGURATION_STORE_SERVERS" ]] && abort "Configuration servers"
[[ -z "$BROKER__BOOKKEEPER_METADATA_SERVICE_URI" ]] && abort "Bookkeeper metadata service URI"
[[ -z "$CLIENT__WEB_SERVICE_URL" ]] && abort "Client web service URL"
[[ -z "$CLIENT__BROKER_SERVICE_URL" ]] && abort "Client broker service URL"

#::END:: 
